name: Backend CI

on:
    push:
        branches:
            - '**'
    pull_request:
        branches: 
            - master

jobs:
    build:
        name: Build the program
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.22.5'
            
            - name: Install dependencies
              run: |
                cd backend
                go mod tidy

            - name: Build
              run: |
                cd backend
                make build  

    test:
      name: Run tests
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Setup Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.22.5'

        - name: Install dependencies
          run: |
            cd backend
            go mod tidy

        - name: Tests
          run: |
            cd backend
            make test

    lint:
      name: Run linter
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Setup Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.22.5'
        
        - name: Install golangci-lint
          run: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.61.0

        - name: Lint
          run: |
            cd backend
            make lint