name: Backend CI

on:
    push:
        branches:
            - '**'
    pull_request:
        branches: 
            - master

jobs:
    build:
        name: Build the program
        runs-on: ubuntu-latest
        needs: test_and_lint

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.22.5'
            
            - name: Install dependencies
              run: |
                cd backend
                go mod tidy

            - name: Build
              run: |
                cd backend
                make build

    test_and_lint:
      name: Run tests and lint
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Setup Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.22.5'

        - name: Install project dependencies
          run: |
            cd backend
            go mod tidy

        - name: Tests
          run: |
            cd backend
            make test
          
        - name: Lint
          uses: golangci/golangci-lint-action@v6
          with:
            version: v1.60
            working-directory: ./backend