name: Backend CI

on:
    push:
        branches:
            - '**'
    pull_request:
        branches: 
            - master

jobs:
    build:
        name: Build the program
        runs-on: ununtu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.23.1'
            
            - name: Install dependencies
              run: go mod tidy

            - name: Build
              run: |
                cd backend
                make build
            
        

    
